/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_management_system1;

import java.io.IOException;
import java.util.function.Predicate;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.util.function.Function;

/**
 *
 * @author Laptop
 */
public class AddMember extends javax.swing.JFrame {

    /**
     * Creates new form AddMember
     */
    public AddMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Namelbl1 = new javax.swing.JLabel();
        txtcustname = new javax.swing.JTextField();
        MobLbl2 = new javax.swing.JLabel();
        txtphone_no = new javax.swing.JTextField();
        EmailLbl1 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        NewMemberlbl = new javax.swing.JLabel();
        ResetLbl = new javax.swing.JLabel();
        Savelbl = new javax.swing.JLabel();
        CloseLbl = new javax.swing.JLabel();
        NewWall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(175, 100));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Namelbl1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Namelbl1.setForeground(new java.awt.Color(255, 255, 255));
        Namelbl1.setText("Customer Name");
        getContentPane().add(Namelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 20));

        txtcustname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtcustname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 240, -1));

        MobLbl2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MobLbl2.setForeground(new java.awt.Color(255, 255, 255));
        MobLbl2.setText("Mobile No.");
        getContentPane().add(MobLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtphone_no.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtphone_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 240, -1));

        EmailLbl1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EmailLbl1.setForeground(new java.awt.Color(255, 255, 255));
        EmailLbl1.setText("Email");
        getContentPane().add(EmailLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        txtemail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 240, -1));

        NewMemberlbl.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        NewMemberlbl.setForeground(new java.awt.Color(255, 255, 255));
        NewMemberlbl.setText("Add Customer");
        getContentPane().add(NewMemberlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        ResetLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reset.png"))); // NOI18N
        ResetLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetLblMouseClicked(evt);
            }
        });
        getContentPane().add(ResetLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, 70));

        Savelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save.png"))); // NOI18N
        Savelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SavelblMouseClicked(evt);
            }
        });
        getContentPane().add(Savelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, 70));

        CloseLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close1.png"))); // NOI18N
        CloseLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLblMouseClicked(evt);
            }
        });
        getContentPane().add(CloseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        NewWall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bck1.jpg"))); // NOI18N
        getContentPane().add(NewWall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new MainManager().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void ResetLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetLblMouseClicked
        txtcustname.setText("");
        txtphone_no.setText("");
        txtemail.setText("");
    }//GEN-LAST:event_ResetLblMouseClicked

    private void CloseLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLblMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseLblMouseClicked
    static Predicate<String> isNotEmpty = str -> !str.isEmpty();
    static Predicate<String> isAlpha = str -> str.matches("[a-zA-Z\\s']+");
    static Predicate<String> isValidEmail = email -> {
        final String regex =
                "^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}";
        final Pattern pattern = Pattern.compile(regex);
        return pattern.matcher(email).matches();    
    };
    
    public boolean validation(String name, String email, String phone_no){
        return validateempty(name, email, phone_no) && validateformat(name, email);
    }
    public boolean validateempty(String name, String email, String phone_no){
        return !(name.isEmpty() && email.isEmpty() && phone_no.isEmpty());
    }
    public boolean validateformat(String name,String email){
        return (isValidEmail.test(email) && isAlpha.test(name));
    }    
    private void SavelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SavelblMouseClicked
        String custName = txtcustname.getText();
        String email = txtemail.getText();
        String phoneNo = txtphone_no.getText();
        
        if(validation(custName,email,phoneNo)==false){
            JOptionPane.showMessageDialog(null,"Please fill in all the field and enter data in the correct format","Error",JOptionPane.WARNING_MESSAGE);
        }else {
            manager manager=new manager();
            try {
                customer customer=new customer();
                customer.cust_reg(txtcustname.getText(),txtphone_no.getText(),txtemail.getText());
                txtcustname.setText("");
                txtphone_no.setText("");
                txtemail.setText("");
            } catch (IOException ex) {
                Logger.getLogger(RegisterManager.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SavelblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseLbl;
    private javax.swing.JLabel EmailLbl1;
    private javax.swing.JLabel MobLbl2;
    private javax.swing.JLabel Namelbl1;
    private javax.swing.JLabel NewMemberlbl;
    private javax.swing.JLabel NewWall;
    private javax.swing.JLabel ResetLbl;
    private javax.swing.JLabel Savelbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtcustname;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtphone_no;
    // End of variables declaration//GEN-END:variables
}
