/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_management_system1;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Laptop
 */
public class EditProfile extends javax.swing.JFrame {

    /**
     * Creates new form EditProfile
     */
    public EditProfile(String name) {
        
        initComponents();
        lbltrainer.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bcklbl = new javax.swing.JLabel();
        TitleLbl = new javax.swing.JLabel();
        Usr2Lbl1 = new javax.swing.JLabel();
        txtconfirm = new javax.swing.JTextField();
        MobNoLbl1 = new javax.swing.JLabel();
        txtphone_no = new javax.swing.JTextField();
        Emaillbl = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        UpdLbl = new javax.swing.JLabel();
        ClsLbl = new javax.swing.JLabel();
        Usr2Lbl2 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        Usr2Lbl3 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        lbltrainer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(175, 100));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bcklbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        Bcklbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BcklblMouseClicked(evt);
            }
        });
        getContentPane().add(Bcklbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        TitleLbl.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        TitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        TitleLbl.setText("Edit Profile");
        getContentPane().add(TitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        Usr2Lbl1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Usr2Lbl1.setForeground(new java.awt.Color(255, 255, 255));
        Usr2Lbl1.setText("Confirm Password");
        getContentPane().add(Usr2Lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        txtconfirm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfirmActionPerformed(evt);
            }
        });
        getContentPane().add(txtconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 210, -1));

        MobNoLbl1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MobNoLbl1.setForeground(new java.awt.Color(255, 255, 255));
        MobNoLbl1.setText("Mobile No.");
        getContentPane().add(MobNoLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txtphone_no.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtphone_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphone_noActionPerformed(evt);
            }
        });
        getContentPane().add(txtphone_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 210, -1));

        Emaillbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Emaillbl.setForeground(new java.awt.Color(255, 255, 255));
        Emaillbl.setText("Email");
        getContentPane().add(Emaillbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        txtemail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 210, -1));

        UpdLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Update22.png"))); // NOI18N
        UpdLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdLblMouseClicked(evt);
            }
        });
        getContentPane().add(UpdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        ClsLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close1.png"))); // NOI18N
        ClsLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClsLblMouseClicked(evt);
            }
        });
        getContentPane().add(ClsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        Usr2Lbl2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Usr2Lbl2.setForeground(new java.awt.Color(255, 255, 255));
        Usr2Lbl2.setText("Username");
        getContentPane().add(Usr2Lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtusername.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 210, -1));

        Usr2Lbl3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Usr2Lbl3.setForeground(new java.awt.Color(255, 255, 255));
        Usr2Lbl3.setText("New Password");
        getContentPane().add(Usr2Lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        txtpassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 210, -1));

        lbltrainer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bck1.jpg"))); // NOI18N
        getContentPane().add(lbltrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BcklblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcklblMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new MainTrainer(lbltrainer.getText()).setVisible(true);
    }//GEN-LAST:event_BcklblMouseClicked

    private void txtconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmActionPerformed

    private void txtphone_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphone_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphone_noActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void ClsLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClsLblMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ClsLblMouseClicked

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        txtusername.setText(lbltrainer.getText());
        String trainer_name=txtusername.getText();
        manager manager=new manager();
        try {
            String[] trainer_info=manager.trainer_search(trainer_name);
            txtphone_no.setText(trainer_info[1]);
            txtpassword.setText(trainer_info[0]);
            txtemail.setText(trainer_info[2]);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(EditProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void UpdLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdLblMouseClicked
        String regex = "^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}";  
        Pattern pattern=Pattern.compile(regex);
        Matcher matcher=pattern.matcher(txtemail.getText());
        if(txtusername.getText().isEmpty()| txtemail.getText().isEmpty()|txtphone_no.getText().isEmpty()|txtpassword.getText().isEmpty()|txtconfirm.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please fill up all the field","Fields not fill up.",JOptionPane.ERROR_MESSAGE);
        }else if(!txtusername.getText().matches("[a-zA-Z\\s']+")|matcher.matches()==false|txtphone_no.getText().matches("^[a-zA-Z]*$")){
            JOptionPane.showMessageDialog(null,"Please enter data in the correct format","Invalid Data",JOptionPane.WARNING_MESSAGE);
        }else if(!txtpassword.getText().equals(txtconfirm.getText())){
            JOptionPane.showMessageDialog(null,"Please enter the correct password","Invalid Password",JOptionPane.WARNING_MESSAGE);
        }else{
            manager manager=new manager();
            try {
                manager.update(txtusername.getText(),txtpassword.getText(),txtphone_no.getText(), txtemail.getText());
            } catch (IOException ex) {
                Logger.getLogger(EditProfile.class.getName()).log(Level.SEVERE, null, ex);
            }
            String[] trainer_info;
            try {
                trainer_info = manager.trainer_search(lbltrainer.getText());
                txtphone_no.setText(trainer_info[1]);
                txtpassword.setText(trainer_info[0]);
                txtemail.setText(trainer_info[2]);
                txtconfirm.setText("");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(EditProfile.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_UpdLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bcklbl;
    private javax.swing.JLabel ClsLbl;
    private javax.swing.JLabel Emaillbl;
    private javax.swing.JLabel MobNoLbl1;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JLabel UpdLbl;
    private javax.swing.JLabel Usr2Lbl1;
    private javax.swing.JLabel Usr2Lbl2;
    private javax.swing.JLabel Usr2Lbl3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbltrainer;
    private javax.swing.JTextField txtconfirm;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtphone_no;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
