/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_management_system1;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Laptop
 */
public class Feedbacks extends javax.swing.JFrame {

    /**
     * Creates new form Feedbacks
     */
    public Feedbacks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLbck = new javax.swing.JLabel();
        PayTitle = new javax.swing.JLabel();
        LBLClose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtsesid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareafeedback = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(175, 100));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBLbck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        LBLbck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBLbckMouseClicked(evt);
            }
        });
        getContentPane().add(LBLbck, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 0, -1, -1));

        PayTitle.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        PayTitle.setForeground(new java.awt.Color(255, 255, 255));
        PayTitle.setText("Feedbacks");
        getContentPane().add(PayTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        LBLClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close1.png"))); // NOI18N
        LBLClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBLCloseMouseClicked(evt);
            }
        });
        getContentPane().add(LBLClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(936, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Session ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        txtsesid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtsesid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsesidActionPerformed(evt);
            }
        });
        getContentPane().add(txtsesid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 220, -1));

        txtareafeedback.setColumns(20);
        txtareafeedback.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtareafeedback.setRows(5);
        jScrollPane1.setViewportView(txtareafeedback);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 540, 250));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Feedback");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bck1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LBLbckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLbckMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new MainManager().setVisible(true);
    }//GEN-LAST:event_LBLbckMouseClicked

    private void LBLCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LBLCloseMouseClicked

    private void txtsesidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsesidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsesidActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        manager manager=new manager();
        String sesid=txtsesid.getText();
        String feedback=txtareafeedback.getText();
        
        try {
            manager.feedback(sesid,feedback);
            txtsesid.setText("");
            txtareafeedback.setText("");
        } catch (IOException ex) {
            Logger.getLogger(Feedbacks.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feedbacks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feedbacks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feedbacks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feedbacks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feedbacks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLClose;
    private javax.swing.JLabel LBLbck;
    private javax.swing.JLabel PayTitle;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtareafeedback;
    private javax.swing.JTextField txtsesid;
    // End of variables declaration//GEN-END:variables
}
