package gym_management_system1;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Laptop
 */
public class Login extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblincorrect = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        chkshow = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblregister = new javax.swing.JLabel();
        lbllogin = new javax.swing.JLabel();
        cbposition = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, -1, -1));

        lblincorrect.setBackground(new java.awt.Color(0, 0, 0));
        lblincorrect.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblincorrect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/warning.png"))); // NOI18N
        lblincorrect.setText("Incorrect username or password");
        lblincorrect.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblincorrectFocusGained(evt);
            }
        });
        getContentPane().add(lblincorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, -1, -1));

        txtusername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtusername.setText("Enter username");
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 268, -1));

        txtpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpassword.setText("Enter password");
        txtpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasswordFocusLost(evt);
            }
        });
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 268, -1));

        chkshow.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        chkshow.setForeground(new java.awt.Color(255, 255, 255));
        chkshow.setText("Show password");
        chkshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkshowActionPerformed(evt);
            }
        });
        getContentPane().add(chkshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, -1, -1));

        lblregister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reg1.png"))); // NOI18N
        lblregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblregisterMouseClicked(evt);
            }
        });
        getContentPane().add(lblregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, -1, 40));

        lbllogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login1212.png"))); // NOI18N
        lbllogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblloginMouseClicked(evt);
            }
        });
        getContentPane().add(lbllogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 110, 40));

        cbposition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Trainner" }));
        getContentPane().add(cbposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 140, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background1.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkshowActionPerformed
        // TODO add your handling code here:
        if(chkshow.isSelected())
        {
            txtpassword.setEchoChar((char)0);
        }
        else
        {
            txtpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_chkshowActionPerformed

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusGained
        // TODO add your handling code here:
        lblincorrect.setVisible(false);
        if(txtusername.getText().equals("Enter username"))
        {
            txtusername.setText("");
            txtusername.setForeground(new Color (0,118,221));
        }
    }//GEN-LAST:event_txtusernameFocusGained

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
        // TODO add your handling code here:
        lblincorrect.setVisible(false);
        if(txtusername.getText().equals(""))
        {
            txtusername.setText("Enter username");
            txtusername.setForeground(new Color (0,118,221));
        }
    }//GEN-LAST:event_txtusernameFocusLost

    private void txtpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusGained
        // TODO add your handling code here:
        lblincorrect.setVisible(false);
        if(txtpassword.getText().equals("Enter password"))
        {
            txtpassword.setText("");
            txtpassword.setForeground(new Color (0,118,221));
        }
    }//GEN-LAST:event_txtpasswordFocusGained

    private void txtpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusLost
        // TODO add your handling code here:
        lblincorrect.setVisible(false);
        if(txtpassword.getText().equals(""))
        {
            txtpassword.setText("Enter password");
            txtpassword.setForeground(new Color (0,118,221));
        }
    }//GEN-LAST:event_txtpasswordFocusLost

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void lblincorrectFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblincorrectFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_lblincorrectFocusGained

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void lblloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblloginMouseClicked
        
        try {
            // TODO add your handling code here:
            login();
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblloginMouseClicked

    private void lblregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregisterMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new RegisterManager().setVisible(true);

    }//GEN-LAST:event_lblregisterMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lblincorrect.setVisible(false);
    }//GEN-LAST:event_formWindowActivated
                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    public void login()throws IOException{
        String name=txtusername.getText();
        String password=txtpassword.getText();
        String in_out="in";
        String status;
        manager manager=new manager();

        File trainermanager=new File("trainermanager.txt");
        trainermanager.createNewFile();
        
        Scanner input=new Scanner(trainermanager);
        while(input.hasNext()){
            String record=input.nextLine();
            String[] details=record.split(",");
            
            if(details[0].equals(name)&&details[1].equals(password)){
                if(cbposition.getSelectedItem().toString()=="Manager"){
                    new MainManager().setVisible(true);
                    this.setVisible(false);
                }else{
                    System.out.println(name);
                    new MainTrainer(txtusername.getText()).setVisible(true);
                    
                    this.setVisible(false);
                }
                this.setVisible(false);
                status="success";
                manager.log_record(name,in_out,status);
        
            }else if(input.hasNext()==false | !details[1].equals(name) | !details[2].equals(password)){
                lblincorrect.show();
                txtusername.setText("");
                txtpassword.setText("");
                status="fail";
                manager.log_record(name,in_out,status);
            }
        }
        input.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbposition;
    private javax.swing.JCheckBox chkshow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblincorrect;
    private javax.swing.JLabel lbllogin;
    private javax.swing.JLabel lblregister;
    private javax.swing.JPasswordField txtpassword;
    public javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
