/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_management_system1;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Laptop
 */
public class Payment1 extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment1(String name) {
        initComponents();
        lbltrainer.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLClose = new javax.swing.JLabel();
        LBLbck = new javax.swing.JLabel();
        PayTitle = new javax.swing.JLabel();
        srchLbl = new javax.swing.JLabel();
        Username3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Username4 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        cbsesid = new javax.swing.JComboBox<>();
        Username5 = new javax.swing.JLabel();
        Username6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblsesid = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblcust = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        lblduration = new javax.swing.JLabel();
        lblprice = new javax.swing.JLabel();
        lblbalance = new javax.swing.JLabel();
        lbltrainer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(175, 100));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBLClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close1.png"))); // NOI18N
        LBLClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBLCloseMouseClicked(evt);
            }
        });
        getContentPane().add(LBLClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(936, 0, -1, -1));

        LBLbck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        LBLbck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBLbckMouseClicked(evt);
            }
        });
        getContentPane().add(LBLbck, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 0, -1, -1));

        PayTitle.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        PayTitle.setForeground(new java.awt.Color(255, 255, 255));
        PayTitle.setText("Payment");
        getContentPane().add(PayTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        srchLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        getContentPane().add(srchLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        Username3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Username3.setForeground(new java.awt.Color(255, 255, 255));
        Username3.setText("Sessions");
        getContentPane().add(Username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reset.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        Username4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Username4.setForeground(new java.awt.Color(255, 255, 255));
        Username4.setText("Amount to pay");
        getContentPane().add(Username4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        txtamount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 191, -1));

        cbsesid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbsesid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbsesidItemStateChanged(evt);
            }
        });
        getContentPane().add(cbsesid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 190, -1));

        Username5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Username5.setForeground(new java.awt.Color(255, 255, 255));
        Username5.setText("Sessions");
        getContentPane().add(Username5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        Username6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Username6.setForeground(new java.awt.Color(255, 255, 255));
        Username6.setText("Sessions");
        getContentPane().add(Username6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Session ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Balance:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Time:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        lblsesid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblsesid.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblsesid, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Customer:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Trainer:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Duration:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Price");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        lblcust.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblcust.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblcust, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        lbldate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbldate.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));

        lbltime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbltime.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, -1, -1));

        lblduration.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblduration.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblduration, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, -1, -1));

        lblprice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblprice.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, -1, -1));

        lblbalance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblbalance.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblbalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, -1, -1));

        lbltrainer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbltrainer.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbltrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bck1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, -1));

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LBLCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LBLCloseMouseClicked

    private void LBLbckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLbckMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new MainTrainer(lbltrainer.getText()).setVisible(true);
    }//GEN-LAST:event_LBLbckMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        txtamount.setText("");
        lblsesid.setText("");
        lblcust.setText("");
        lbltrainer.setText("");
        lbldate.setText("");
        lbltime.setText("");
        lblprice.setText("");
        lblbalance.setText("");
        lblduration.setText("");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        txtamount.setEnabled(false);
        cbsesid.removeAllItems();
        txtamount.setText("");
        lblsesid.setText("");
        lblcust.setText("");
        lbltrainer.setText("");
        lbldate.setText("");
        lbltime.setText("");
        lblprice.setText("");
        lblbalance.setText("");
        lblduration.setText("");
        try {
            getValue();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Payment1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_formWindowActivated

    private void cbsesidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbsesidItemStateChanged
        try {
            search_session(cbsesid.getSelectedItem().toString());
            txtamount.setEnabled(true);
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Payment1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbsesidItemStateChanged

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        manager manager=new manager();
        try {
            manager.payment(cbsesid.getSelectedItem().toString(), Double.parseDouble(txtamount.getText()));
            getValue();
        } catch (IOException ex) {
            Logger.getLogger(Payment1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    public void getValue() throws FileNotFoundException{
        cbsesid.removeAllItems();
        File session=new File("session.txt");
        Scanner input=new Scanner(session);  
        while(input.hasNext()){
            String record=input.nextLine();
            String[] details=record.split(",");
            if(details[8].equals("false")){
                cbsesid.addItem(details[0]);
            }
        }
        input.close();
        };
    
    public void search_session(String id) throws FileNotFoundException{
        File session=new File("session.txt");
        Scanner input=new Scanner(session);  
        while(input.hasNext()){
            String record=input.nextLine();
            String[] details=record.split(",");
            if(details[0].equals(id)){
                lblsesid.setText(details[0]);
                lblcust.setText(details[2]);
                lbltrainer.setText(details[1]);
                lbldate.setText(details[3]);
                lbltime.setText(details[4]);
                lblduration.setText(details[5]);
                lblprice.setText(details[6]);
                lblbalance.setText(details[7]);
            }
        }
        input.close();
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLClose;
    private javax.swing.JLabel LBLbck;
    private javax.swing.JLabel PayTitle;
    private javax.swing.JLabel Username3;
    private javax.swing.JLabel Username4;
    private javax.swing.JLabel Username5;
    private javax.swing.JLabel Username6;
    private javax.swing.JComboBox<String> cbsesid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblbalance;
    private javax.swing.JLabel lblcust;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblduration;
    private javax.swing.JLabel lblprice;
    private javax.swing.JLabel lblsesid;
    private javax.swing.JLabel lbltime;
    private javax.swing.JLabel lbltrainer;
    private javax.swing.JLabel srchLbl;
    private javax.swing.JTextField txtamount;
    // End of variables declaration//GEN-END:variables
}
