/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_management_system1;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.regex.*;
import java.util.*;

/**
 *
 * @author Laptop
 */
public class RegisterManager extends javax.swing.JFrame {

    /**
     * Creates new form RegisterManager
     */
    public RegisterManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Namelbl1 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        MobLbl2 = new javax.swing.JLabel();
        txtphone_no = new javax.swing.JTextField();
        EmailLbl1 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        Namelbl2 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        Namelbl = new javax.swing.JLabel();
        txtconfirm = new javax.swing.JTextField();
        Savelbl = new javax.swing.JLabel();
        ResetLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(175, 100));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Register For Trainer and Manager");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close1.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        Namelbl1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Namelbl1.setForeground(new java.awt.Color(255, 255, 255));
        Namelbl1.setText("Username");
        getContentPane().add(Namelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, 20));

        txtusername.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, -1));

        MobLbl2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MobLbl2.setForeground(new java.awt.Color(255, 255, 255));
        MobLbl2.setText("Mobile No.");
        getContentPane().add(MobLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        txtphone_no.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtphone_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphone_noActionPerformed(evt);
            }
        });
        getContentPane().add(txtphone_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 240, -1));

        EmailLbl1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EmailLbl1.setForeground(new java.awt.Color(255, 255, 255));
        EmailLbl1.setText("Email");
        getContentPane().add(EmailLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        txtemail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 240, -1));

        Namelbl2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Namelbl2.setForeground(new java.awt.Color(255, 255, 255));
        Namelbl2.setText("Password");
        getContentPane().add(Namelbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 100, 20));

        txtpassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 230, -1));

        Namelbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Namelbl.setForeground(new java.awt.Color(255, 255, 255));
        Namelbl.setText("Confirm Password");
        getContentPane().add(Namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 160, 20));

        txtconfirm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 230, -1));

        Savelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save.png"))); // NOI18N
        Savelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SavelblMouseClicked(evt);
            }
        });
        getContentPane().add(Savelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, 70));

        ResetLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reset.png"))); // NOI18N
        ResetLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetLblMouseClicked(evt);
            }
        });
        getContentPane().add(ResetLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bck1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetLblMouseClicked
        txtusername.setText("");
        txtphone_no.setText("");
        txtemail.setText("");
        txtpassword.setText("");
        txtconfirm.setText("");
        txtusername.requestFocus();
    }//GEN-LAST:event_ResetLblMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtphone_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphone_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphone_noActionPerformed

    private void SavelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SavelblMouseClicked
        String regex = "^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}";  
        Pattern pattern=Pattern.compile(regex);
        Matcher matcher=pattern.matcher(txtemail.getText());
        if(txtusername.getText().isEmpty()| txtemail.getText().isEmpty()|txtphone_no.getText().isEmpty()|txtpassword.getText().isEmpty()|txtconfirm.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please fill up all the field","Fields not fill up.",JOptionPane.ERROR_MESSAGE);
        }else if(!txtusername.getText().matches("[a-zA-Z\\s']+")|matcher.matches()==false|txtphone_no.getText().matches("^[a-zA-Z]*$")){
            JOptionPane.showMessageDialog(null,"Please enter data in the correct format","Invalid Data",JOptionPane.WARNING_MESSAGE);
        }else if(!txtpassword.getText().equals(txtconfirm.getText())){
            JOptionPane.showMessageDialog(null,"Please enter the correct password","Invalid Password",JOptionPane.WARNING_MESSAGE);
        }else{
            manager manager=new manager();
            try {
                manager.reg(txtusername.getText(),txtpassword.getText(),txtphone_no.getText(),txtemail.getText());
                txtusername.setText("");
                txtpassword.setText("");
                txtphone_no.setText("");
                txtemail.setText("");
                txtconfirm.setText("");
            } catch (IOException ex) {
                Logger.getLogger(RegisterManager.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SavelblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailLbl1;
    private javax.swing.JLabel MobLbl2;
    private javax.swing.JLabel Namelbl;
    private javax.swing.JLabel Namelbl1;
    private javax.swing.JLabel Namelbl2;
    private javax.swing.JLabel ResetLbl;
    private javax.swing.JLabel Savelbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtconfirm;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtphone_no;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
