/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_management_system1;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Laptop
 */
public class SearchCus extends javax.swing.JFrame {

    /**
     * Creates new form SearchUser
     */
    public SearchCus() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MemberListLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lbltrainer = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblphone_no = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtname1 = new javax.swing.JTextField();
        txtphone_no = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        lblreset = new javax.swing.JLabel();
        lblsave = new javax.swing.JLabel();
        lbldelete = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(175, 100));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        MemberListLbl.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        MemberListLbl.setForeground(new java.awt.Color(255, 255, 255));
        MemberListLbl.setText("Search Customer");
        getContentPane().add(MemberListLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        txtname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, -1));

        lbltrainer.setText("jLabel5");
        getContentPane().add(lbltrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone Number ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        lblphone_no.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblphone_no.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblphone_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        lblemail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblemail.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        txtname1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtname1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, -1));

        txtphone_no.setToolTipText("");
        txtphone_no.setPreferredSize(new java.awt.Dimension(7, 23));
        getContentPane().add(txtphone_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 200, -1));

        txtemail.setToolTipText("");
        txtemail.setPreferredSize(new java.awt.Dimension(7, 23));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 200, -1));

        lblreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reset.png"))); // NOI18N
        lblreset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblresetMouseClicked(evt);
            }
        });
        getContentPane().add(lblreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        lblsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save.png"))); // NOI18N
        lblsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsaveMouseClicked(evt);
            }
        });
        getContentPane().add(lblsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        lbldelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        lbldelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldeleteMouseClicked(evt);
            }
        });
        getContentPane().add(lbldelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bck1.jpg"))); // NOI18N
        background.setToolTipText("");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new MainManager().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lbltrainer.setVisible(false);
        txtphone_no.setEnabled(false);
        txtemail.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if(txtname.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please fill in the customer name","Field not fill up",JOptionPane.ERROR_MESSAGE);
        }else{
            trainer trainer=new trainer();
            try {
                String[] cus_info = trainer.cust_search(txtname.getText());
                txtphone_no.setText(cus_info[1]);
                txtemail.setText(cus_info[2]);
                if(cus_info!=null){
                    txtphone_no.setEnabled(true);
                    txtemail.setEnabled(true);
                }
{
                    
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SearchCus.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void txtname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtname1ActionPerformed

    private void lblresetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblresetMouseClicked
        lbltrainer.setText("");
        txtphone_no.setText("");
        txtemail.setText("");
    }//GEN-LAST:event_lblresetMouseClicked

    private void lblsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsaveMouseClicked
        String name=txtname.getText();
        String phone_no=txtphone_no.getText();
        String email=txtemail.getText();
        String regex = "^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}";  
        Pattern pattern=Pattern.compile(regex);
        Matcher matcher=pattern.matcher(email);
        
        if(txtname.getText().isEmpty()| txtemail.getText().isEmpty()|txtphone_no.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please fill up all the field","Fields not fill up.",JOptionPane.ERROR_MESSAGE);
        }else {
            customer customer=new customer();
            try {
                customer.cust_update(name, phone_no, email);
                txtname.setText("");
                txtphone_no.setText("");
                txtemail.setText("");
            } catch (IOException ex) {
                Logger.getLogger(RegisterManager.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_lblsaveMouseClicked

    private void lbldeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldeleteMouseClicked
        String name=txtname.getText();
        String phone_no=txtphone_no.getText();
        String email=txtemail.getText();
        
        customer customer=new customer();
        if(txtname.getText().isEmpty()| txtemail.getText().isEmpty()|txtphone_no.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please fill up all the field","Fields not fill up.",JOptionPane.ERROR_MESSAGE);
        }else {
            
            try {
                customer.cust_del(name);
                txtname.setText("");
                txtphone_no.setText("");
                txtemail.setText("");
            } catch (IOException ex) {
                Logger.getLogger(RegisterManager.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lbldeleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchCus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchCus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchCus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchCus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MemberListLbl;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbldelete;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblphone_no;
    private javax.swing.JLabel lblreset;
    private javax.swing.JLabel lblsave;
    private javax.swing.JLabel lbltrainer;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtname1;
    private javax.swing.JTextField txtphone_no;
    // End of variables declaration//GEN-END:variables
}
