/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_management_system1;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Laptop
 */
public class UpdateDeleteMemberTrainer extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDeleteMember
     */
    public UpdateDeleteMemberTrainer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClsLbl = new javax.swing.JLabel();
        Bcklbl = new javax.swing.JLabel();
        TitleLbl = new javax.swing.JLabel();
        SearchLbl = new javax.swing.JLabel();
        Emaillbl = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        Usr2Lbl1 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        MobNoLbl1 = new javax.swing.JLabel();
        txtphone_no = new javax.swing.JTextField();
        UpdLbl = new javax.swing.JLabel();
        RstLBL = new javax.swing.JLabel();
        DltLbl = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(175, 100));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClsLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close1.png"))); // NOI18N
        ClsLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClsLblMouseClicked(evt);
            }
        });
        getContentPane().add(ClsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        Bcklbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        Bcklbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BcklblMouseClicked(evt);
            }
        });
        getContentPane().add(Bcklbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        TitleLbl.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        TitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        TitleLbl.setText("Update&Delete Member/Trainer");
        getContentPane().add(TitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        SearchLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        SearchLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchLblMouseClicked(evt);
            }
        });
        getContentPane().add(SearchLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        Emaillbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Emaillbl.setForeground(new java.awt.Color(255, 255, 255));
        Emaillbl.setText("Email");
        getContentPane().add(Emaillbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        txtemail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 210, -1));

        Usr2Lbl1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Usr2Lbl1.setForeground(new java.awt.Color(255, 255, 255));
        Usr2Lbl1.setText("Username");
        getContentPane().add(Usr2Lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtusername.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 210, -1));

        MobNoLbl1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MobNoLbl1.setForeground(new java.awt.Color(255, 255, 255));
        MobNoLbl1.setText("Mobile No.");
        getContentPane().add(MobNoLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        txtphone_no.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtphone_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphone_noActionPerformed(evt);
            }
        });
        getContentPane().add(txtphone_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 210, -1));

        UpdLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Update22.png"))); // NOI18N
        UpdLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdLblMouseClicked(evt);
            }
        });
        getContentPane().add(UpdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        RstLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reset.png"))); // NOI18N
        RstLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RstLBLMouseClicked(evt);
            }
        });
        getContentPane().add(RstLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        DltLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        DltLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DltLblMouseClicked(evt);
            }
        });
        getContentPane().add(DltLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bck1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jFormattedTextField1.setText("jFormattedTextField1");
        getContentPane().add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClsLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClsLblMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ClsLblMouseClicked

    private void BcklblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcklblMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new MainManager().setVisible(true);
    }//GEN-LAST:event_BcklblMouseClicked

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtphone_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphone_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphone_noActionPerformed

    private void RstLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RstLBLMouseClicked
        txtusername.setText("");
        txtpassword.setText("");
        txtphone_no.setText("");
        txtemail.setText("");
        txtpassword.setEnabled(false);
        txtphone_no.setEnabled(false);
        txtemail.setEnabled(false);
    }//GEN-LAST:event_RstLBLMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        txtpassword.setText("");
        txtphone_no.setText("");
        txtemail.setText("");
        txtpassword.setEnabled(false);
        txtphone_no.setEnabled(false);
        txtemail.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void SearchLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchLblMouseClicked
        manager manager=new manager();
        try {
            String[] trainer_info=manager.trainer_search(txtusername.getText().toString());
            txtpassword.setText(trainer_info[0]);
            txtphone_no.setText(trainer_info[1]);
            txtemail.setText(trainer_info[2]);
            txtpassword.setEnabled(true);
            txtphone_no.setEnabled(true);
            txtemail.setEnabled(true);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(UpdateDeleteMemberTrainer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SearchLblMouseClicked

    private void UpdLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdLblMouseClicked
        manager manager=new manager();
        try {
            manager.update(txtusername.getText(), txtpassword.getText(), txtphone_no.getText(), txtemail.getText());
        } catch (IOException ex) {
            Logger.getLogger(UpdateDeleteMemberTrainer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdLblMouseClicked

    private void DltLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DltLblMouseClicked
        manager manager=new manager();
        try {
            manager.trainer_del(txtusername.getText());
        } catch (IOException ex) {
            Logger.getLogger(UpdateDeleteMemberTrainer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        txtusername.setText("");
    }//GEN-LAST:event_DltLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteMemberTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteMemberTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteMemberTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteMemberTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDeleteMemberTrainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bcklbl;
    private javax.swing.JLabel ClsLbl;
    private javax.swing.JLabel DltLbl;
    private javax.swing.JLabel Emaillbl;
    private javax.swing.JLabel MobNoLbl1;
    private javax.swing.JLabel RstLBL;
    private javax.swing.JLabel SearchLbl;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JLabel UpdLbl;
    private javax.swing.JLabel Usr2Lbl1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtphone_no;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
